import { PresetItem, TaskType } from '../types/verdict';

export interface TaskConfig {
  id: TaskType;
  title: string;
  language: 'python' | 'json';
  languageLabel: string;
  badge: string;
  purpose: string;
  description: string;
  rules: string[];
  presets: PresetItem[];
  defaultCode: string;
}

export const TASK_CONFIGS: Record<TaskType, TaskConfig> = {
  safe_divide: {
    id: 'safe_divide',
    title: 'safe_divide',
    language: 'python',
    languageLabel: 'Python 3',
    badge: 'Code Verification',
    purpose: 'Verify a Python function named divide() for safety and division-by-zero guards.',
    description:
      'Evaluates AI-generated arithmetic functions to ensure division safety invariants are strictly implemented.',
    rules: [
      'divide() accepts exactly two parameters',
      'A division operation (/) exists',
      'An explicit zero-division guard exists (e.g. if b == 0 / if not b)',
      'The function returns a result',
    ],
    defaultCode: `def divide(a, b):
    if b == 0:
        return None
    return a / b`,
    presets: [
      {
        id: 'sd-pass',
        title: 'Guarded Division (Passing)',
        description: 'Implements full division-by-zero guard with explicit zero handling.',
        expectedVerdict: 'PASS',
        code: `def divide(a, b):
    if b == 0:
        return None
    return a / b`,
      },
      {
        id: 'sd-fail-guard',
        title: 'Unguarded Division (Failing)',
        description: 'Missing explicit zero-division check, causing safety invariant failure.',
        expectedVerdict: 'FAIL',
        code: `def divide(a, b):
    return a / b`,
      },
      {
        id: 'sd-fail-params',
        title: 'Wrong Signature (Failing)',
        description: 'Accepts 3 parameters instead of the required 2.',
        expectedVerdict: 'FAIL',
        code: `def divide(a, b, precision=2):
    if b == 0:
        return 0.0
    return round(a / b, precision)`,
      },
      {
        id: 'sd-error-syntax',
        title: 'Syntax Error (Error)',
        description: 'Invalid Python syntax producing parser error.',
        expectedVerdict: 'ERROR',
        code: `def divide(a, b)
    if b == 0
        return None
    return a / b`,
      },
    ],
  },
  validate_json: {
    id: 'validate_json',
    title: 'validate_json',
    language: 'json',
    languageLabel: 'JSON Schema',
    badge: 'Schema Validation',
    purpose: 'Verify structured JSON generated by an AI agent meets exact schema invariants.',
    description:
      'Evaluates autonomous agent JSON payloads for presence of required keys (name, age) and strict type constraints.',
    rules: [
      "Required field 'name' exists",
      "Required field 'age' exists",
      "'name' is a string",
      "'age' is an integer",
    ],
    defaultCode: `{\n  "name": "Alice",\n  "age": 22\n}`,
    presets: [
      {
        id: 'vj-pass',
        title: 'Valid Agent Payload (Passing)',
        description: 'Clean JSON payload with valid string "name" and integer "age".',
        expectedVerdict: 'PASS',
        code: `{\n  "name": "Alice",\n  "age": 22\n}`,
      },
      {
        id: 'vj-fail-types',
        title: 'Invalid Field Types (Failing)',
        description: '"name" is numeric and "age" is missing, violating schema.',
        expectedVerdict: 'FAIL',
        code: `{\n  "name": 123\n}`,
      },
      {
        id: 'vj-fail-age-type',
        title: 'Float/String Age (Failing)',
        description: '"age" provided as a string instead of an integer.',
        expectedVerdict: 'FAIL',
        code: `{\n  "name": "Bob",\n  "age": "twenty-five"\n}`,
      },
      {
        id: 'vj-error-malformed',
        title: 'Malformed JSON (Error)',
        description: 'Unclosed quotes and invalid trailing syntax.',
        expectedVerdict: 'ERROR',
        code: `{\n  "name": "Alice",\n  "age": 22,,\n}`,
      },
    ],
  },
};
