import { PresetItem, TaskType } from '../types/verdict';

export interface TaskConfig {
  id: TaskType;
  title: string;
  language: 'python' | 'json';
  languageLabel: string;
  badge: string;
  purpose: string;
  description: string;
  rules: string[];
  presets: PresetItem[];
  defaultCode: string;
}

export const TASK_CONFIGS: Record<TaskType, TaskConfig> = {
  safe_divide: {
    id: 'safe_divide',
    title: 'safe_divide',
    language: 'python',
    languageLabel: 'Python 3',
    badge: 'Code Verification',
    purpose:
      'Verify a Python function named divide() for safety and division-by-zero guards.',
    description:
      'Evaluates AI-generated arithmetic functions to ensure division safety invariants are strictly implemented.',
    rules: [
      'divide() accepts exactly two parameters',
      'A division operation (/) exists',
      'An explicit zero-division guard exists (e.g. if b == 0 / if not b)',
      'The function returns a result',
    ],
    defaultCode: `def divide(a, b):
    if b == 0:
        return None
    return a / b`,
    presets: [
      {
        id: 'sd-pass',
        title: 'Guarded Division (Passing)',
        description:
          'Implements full division-by-zero guard with explicit zero handling.',
        expectedVerdict: 'PASS',
        code: `def divide(a, b):
    if b == 0:
        return None
    return a / b`,
      },
      {
        id: 'sd-fail-guard',
        title: 'Unguarded Division (Failing)',
        description:
          'Missing explicit zero-division check, causing safety invariant failure.',
        expectedVerdict: 'FAIL',
        code: `def divide(a, b):
    return a / b`,
      },
      {
        id: 'sd-fail-params',
        title: 'Wrong Signature (Failing)',
        description:
          'Accepts 3 parameters instead of the required 2.',
        expectedVerdict: 'FAIL',
        code: `def divide(a, b, precision=2):
    if b == 0:
        return 0.0
    return round(a / b, precision)`,
      },
      {
        id: 'sd-error-syntax',
        title: 'Syntax Error (Error)',
        description:
          'Invalid Python syntax producing parser error.',
        expectedVerdict: 'ERROR',
        code: `def divide(a, b)
    if b == 0
        return None
    return a / b`,
      },
    ],
  },

  validate_json: {
    id: 'validate_json',
    title: 'validate_json',
    language: 'json',
    languageLabel: 'JSON Schema',
    badge: 'Schema Validation',
    purpose:
      'Verify structured JSON generated by an AI agent meets exact schema invariants.',
    description:
      'Evaluates autonomous agent JSON payloads for presence of required keys (name, age) and strict type constraints.',
    rules: [
      "Required field 'name' exists",
      "Required field 'age' exists",
      "'name' is a string",
      "'age' is an integer",
    ],
    defaultCode: `{
  "name": "Alice",
  "age": 22
}`,
    presets: [
      {
        id: 'vj-pass',
        title: 'Valid Agent Payload (Passing)',
        description:
          'Clean JSON payload with valid string "name" and integer "age".',
        expectedVerdict: 'PASS',
        code: `{
  "name": "Alice",
  "age": 22
}`,
      },
      {
        id: 'vj-fail-types',
        title: 'Invalid Field Types (Failing)',
        description:
          '"name" is numeric and "age" is missing, violating schema.',
        expectedVerdict: 'FAIL',
        code: `{
  "name": 123
}`,
      },
      {
        id: 'vj-fail-age-type',
        title: 'Float/String Age (Failing)',
        description:
          '"age" provided as a string instead of an integer.',
        expectedVerdict: 'FAIL',
        code: `{
  "name": "Bob",
  "age": "twenty-five"
}`,
      },
      {
        id: 'vj-error-malformed',
        title: 'Malformed JSON (Error)',
        description:
          'Unclosed quotes and invalid trailing syntax.',
        expectedVerdict: 'ERROR',
        code: `{
  "name": "Alice",
  "age": 22,,
}`,
      },
    ],
  },

  agent_action: {
    id: 'agent_action',
    title: 'agent_action',
    language: 'json',
    languageLabel: 'Agent Action',
    badge: 'Action Policy',
    purpose:
      'Verify an autonomous agent action against deterministic execution policies before it is trusted.',
    description:
      'Evaluates payment actions against explicit policy invariants before an autonomous agent proceeds.',
    rules: [
      "Action must be 'send_payment'",
      'Payment amount must be a positive number',
      'Payment amount must not exceed 100 USDC',
      'Payment currency must be USDC',
      'Payment recipient must be present',
    ],
    defaultCode: `{
  "action": "send_payment",
  "amount": 50,
  "currency": "USDC",
  "recipient": "ALICE",
  "reason": "Pay invoice"
}`,
    presets: [
      {
        id: 'aa-pass',
        title: 'Allowed Payment (Passing)',
        description:
          'Payment action satisfies all deterministic policy checks.',
        expectedVerdict: 'PASS',
        code: `{
  "action": "send_payment",
  "amount": 50,
  "currency": "USDC",
  "recipient": "ALICE",
  "reason": "Pay invoice"
}`,
      },
      {
        id: 'aa-fail-limit',
        title: 'Over Limit (Failing)',
        description:
          'Payment exceeds the 100 USDC policy limit.',
        expectedVerdict: 'FAIL',
        code: `{
  "action": "send_payment",
  "amount": 150,
  "currency": "USDC",
  "recipient": "ALICE",
  "reason": "Pay invoice"
}`,
      },
      {
        id: 'aa-fail-currency',
        title: 'Wrong Currency (Failing)',
        description:
          'Payment uses a currency other than USDC.',
        expectedVerdict: 'FAIL',
        code: `{
  "action": "send_payment",
  "amount": 50,
  "currency": "USD",
  "recipient": "ALICE",
  "reason": "Pay invoice"
}`,
      },
      {
        id: 'aa-error-malformed',
        title: 'Malformed Action (Error)',
        description:
          'Malformed JSON cannot be evaluated reliably.',
        expectedVerdict: 'ERROR',
        code: `{
  "action": "send_payment",
  "amount": 50,
  "currency": "USDC",
  "recipient": "ALICE",
}`,
      },
    ],
  },
};